### ISSUE TITLE
Tea Cozy Review

### ISSUE THREAD

**Issue by franfranfranfran** [chuneycu2/TeaCozy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 3
* _Comment(s):_ Nice work getting everything laid out nicely in the HTML. You're off to a great start in creating a strong structure for the content on the page. There are a couple areas I noticed for potential improvement-
-It can be tempting to add in extra divs to help section off certain items, but try to avoid adding them in where they are not necessary. For example, do you need a whole extra div section around just the[ location heading text](https://github.com/chuneycu2/TeaCozy/blob/master/index.html#L60-L62)? Look around the page for other spots like this where you could likely make the HTML more concise.
-Take full advantage of flex in the [selection](https://github.com/chuneycu2/TeaCozy/blob/master/index.html#L33-L57) section by putting all 5 items in one flex container and making use of [flex-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) to have them automatically spill onto the next line. This is a good example of the ways in which your HTML structure can influence your CSS.
-A small issue perhaps, but try to add in some well-placed line breaks in your HTML to increase readability. More info about HTML styling in general can be found [here](https://www.w3schools.com/html/html5_syntax.asp). 

### Criteria 2: Visual Layout
* _Score Level:_ 3
* _Comment(s):_ Overall, very close! With just a couple key changes, the page will be laid out exactly like the given spec. The mission and locations sections seem to be a bit off center. Consider setting the max width for these sections on the entire section, instead of on the content inside.
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 3
* _Comment(s):_ Excellent job making use of flex display to help align items throughout the page! Take a look at these places where you're setting that styling. Is there a way to reduce the number of repeated lines in your css? What if we had a flex class that assigns the general stuff needed for flex and then you dive into the more specific details with the section class selector.
Also, consider the info provided in Criteria 1 for how your HTML structure will influence your CSS & how you use flex.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ Great work getting everything styled nicely to match the spec. Everything looks great! Consider making use of an [HTML entity](https://www.w3schools.com/html/html_symbols.asp) to put a copyright symbol on the page at the bottom.
 
### Overall Score: 13/16
Great work on this project. With a few key tweaks, everything will be looking perfect. As a next step, try adjusting the selection section to make use of flex-wrap. Always be looking out for ways to make both the HTML and CSS more readable and concise.
Have fun and keep up the good work!

**Comment by chuneycu2** [comment]
Thank you for this detailed review! I see what you are saying about redundancy with div tags and style declarations in particular. I will work on being more concise as I build. It is tempting to control everything directly instead of setting parent styles and letting them work.

I think I tried the full flex-wrap for the selections section, but got discouraged by the spacing that wasn't consistent (because two items wrapped on the second line and had more space between). Now I see if I had centered them with no space-between, then added padding to each element, I could have done it evenly in one div. 

There were a few parts of the spec that weren't clear to me re: container widths and potential responsiveness. I figured that since we haven't covered responsive design yet, I shouldn't use relative sizing for any of the images or containers. It might be worth noting on the redline mocks that sections sized by pixels wont expand with the page, and that extra space in a larger browser is okay for now. 

Thank you again for taking the time to review my work!
